name: New issue
description: Enter a new issue
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a summary of the issue, from both customer and technical perspectives.
      placeholder: Briefly describe the problem, suggested improvements, or requested functionality.
    validations:
      required: true
# For bugs
  - type: input
    id: version
    attributes:
      label: runZero version (bugs only)
      description: What version was this bug initially noticed in?
      placeholder: v4.1.240102.7
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce (bugs only)
      description: Describe how someone can reproduce the issue.
      placeholder: Mention prerequisites needed, browsers used, steps to carry out.
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior (bugs only)
      description: Describe what should happen.
      placeholder: What output or behavior did you expect?
    validations:
      required: true
  - type: textarea
    id: observed
    attributes:
      label: Observed behavior (bugs only)
      description: Describe what actually happened.
      placeholder: What output or behavior did you get? Include any error messages exactly as they appeared.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Problem severity (bugs only)
      description: How bad a problem is this?
      options:
        - Cosmetic (data correct, feature still works)
        - Minor (broken but workaround exists)
        - Major (one or more product features unusable)
        - Critical (entire product unusable)
      default: 0
    validations:
      required: true
# For a11y
  - type: dropdown
    id: wcag-level
    attributes:
      label: WCAG conformance level (a11y only)
      description: What's the lowest level of WCAG conformance this issue prevents us from achieving?
      options:
        - A
        - AA
        - AAA
      default: 0
    validations:
      required: true
# For all issue types
  - type: textarea
    id: done
    attributes:
      label: Definition of "done"
      description: Specify criteria for closing this issue. For accessibility issues, specify a test procedure.
    validations:
      required: true
  - type: textarea
    id: followup
    attributes:
      label: Followup steps
      description: List any steps to be taken once the work is complete and the issue is closed.
      placeholder: Specify support tickets as SUPPORT-NNNN
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Optionally add references to related issues, background information, commentary, and information about customers impacted.
    validations:
      required: false
  - type: textarea
    id: suggestions
    attributes:
      label: Suggested implementation
      description: Optionally add implementation suggestions.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Please remember to set the labels for the issue appropriately.
