name: ▶️ Do the thing

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: environment

jobs:
  call-reusable-action:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: ${{ inputs.Environment }}
