name: Reusable build step

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  print-stuff:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo environment: ${{ inputs.environment }}
        echo var from environment: ${{ var.SOME_VALUE }}
        echo secret from repo: ${{ secrets.SOME_SECRET }}
