name: Reusable build step

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: environment

jobs:
  print-stuff:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo var from environment: ${{ var.SOME_VALUE }}
        echo secret from repo: ${{ secrets.SOME_SECRET }}
