name: ⚙️  Do actual build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      delete:
        type: boolean
        default: true

jobs:
  print-stuff:
    name: Print some info
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - run: |
        if [ '${{ inputs.delete }}' == 'true' ]; then
          DELETE_OPTION='--delete'
        fi
        echo environment: ${{ inputs.environment }}
        echo var from environment: ${{ vars.SOME_VALUE }}
        echo secret from repo: ${{ secrets.SOME_SECRET }}
        echo delete option: $DELETE_OPTION
        echo ls
        ls -la somefile.txt
        echo git
        git log -1 --format="%ad" -- somefile.txt
        cat somefile.txt
